const fs = require('fs');

const data = {
  "auto-gen-1": ["concept", "HTML/CSS Foundations", "Web Fundamentals Knowledge Checkpoint", 
    "This checkpoint verifies your understanding of HTML semantics, CSS box model, and responsive design principles.",
    "<!DOCTYPE html>\\n<html>\\n<head>\\n<style>\\n.box { box-sizing: border-box; }\\n</style>\\n</head>\\n<body>\\n<div class='box'>Test</div>\\n</body>\\n</html>",
    "Review your semantic tags and ensure your layout is responsive.",
    "What does box-sizing: border-box do?",
    ["Includes padding and border in the element's total width", "Excludes padding from width", "Makes the element a flex container", "Adds a border automatically"], 0,
    "border-box ensures that padding and borders are included in the element's specified width and height."
  ],
  "auto-gen-2": ["project", "DOM", "Interactive DOM Manipulation Project",
    "The DOM (Document Object Model) is a programming interface for web documents. It represents the page so that programs can change the document structure, style, and content. You will build an interactive to-do list.",
    "const btn = document.getElementById('add');\\nbtn.addEventListener('click', () => {\\n  const li = document.createElement('li');\\n  li.textContent = 'New Task';\\n  document.querySelector('ul').appendChild(li);\\n});",
    "Build a task list where you can add, complete, and delete items using vanilla JavaScript DOM methods.",
    "Which method creates a new DOM element?",
    ["document.createElement()", "document.newElement()", "document.addNode()", "window.create()"], 0,
    "document.createElement() creates the HTML element specified by the tag name."
  ],
  "auto-gen-3": ["reflection", "JavaScript", "JavaScript Fundamentals Checkpoint",
    "JavaScript is a synchronous, single-threaded language with a non-blocking event loop. This checkpoint tests closures, scope, and basic event handling.",
    "function closureExample() {\\n  let count = 0;\\n  return () => count++;\\n}",
    "Reflect on how closures preserve scope in your recent projects.",
    "What is a closure?",
    ["A function that has access to its outer function scope even after the outer function has returned", "A way to close the browser window", "A method to end a loop", "A secure way to encrypt data"], 0,
    "Closures allow inner functions to access variables from an enclosing scope."
  ],
  "auto-gen-4": ["concept", "JavaScript", "JavaScript Event Loop & Concurrency Model",
    "The event loop is responsible for executing the code, collecting and processing events, and executing queued sub-tasks. The call stack handles synchronous code, while the task queue handles asynchronous callbacks (like setTimeout).",
    "console.log('1');\\nsetTimeout(() => console.log('2'), 0);\\nPromise.resolve().then(() => console.log('3'));\\nconsole.log('4');\\n// Output: 1, 4, 3, 2",
    "Trace the execution order of synchronous code, promises (microtasks), and setTimeouts (macrotasks) in the provided snippet.",
    "Which queue has higher priority in the event loop?",
    ["Microtask queue (Promises)", "Macrotask queue (setTimeout)", "Render queue", "Callback queue"], 0,
    "The microtask queue is emptied immediately after the currently executing script and before any macrotasks."
  ],
  "auto-gen-5": ["concept", "JavaScript", "Async/Await Control Flow",
    "Async/await is syntactic sugar over Promises, allowing you to write asynchronous code that looks and behaves like synchronous code. An async function always returns a Promise.",
    "async function fetchData() {\\n  try {\\n    const res = await fetch('https://api.example.com/data');\\n    const data = await res.json();\\n    return data;\\n  } catch (err) {\\n    console.error(err);\\n  }\\n}",
    "Rewrite a Promise chain using async/await and wrap it in a try/catch block.",
    "What does the await keyword do?",
    ["Pauses the execution of the async function until the Promise settles", "Stops the entire JavaScript thread", "Automatically retries failed requests", "Makes the function run synchronously"], 0,
    "await pauses the async function execution until the Promise resolves or rejects."
  ],
  "auto-gen-6": ["concept", "JavaScript", "Prototypal Inheritance & the Prototype Chain",
    "JavaScript objects have a special hidden property [[Prototype]] (accessed via __proto__ or Object.getPrototypeOf). When reading a property, if it's missing, JavaScript automatically takes it from the prototype.",
    "const animal = { eats: true };\\nconst rabbit = { jumps: true };\\nrabbit.__proto__ = animal;\\nconsole.log(rabbit.eats); // true",
    "Create a class hierarchy using ES6 classes and inspect their prototype chain in the console.",
    "If an object doesn't have a property, where does JavaScript look next?",
    ["Its prototype", "The global window object", "The Object constructor", "It throws an error immediately"], 0,
    "JavaScript traverses up the prototype chain to find the property."
  ],
  "auto-gen-7": ["concept", "JavaScript", "Memory Management & Garbage Collection",
    "JavaScript automatically allocates memory when objects are created and frees it when they are not used anymore (Garbage Collection). The main algorithm is 'mark-and-sweep', which removes unreachable objects.",
    "let user = { name: 'John' };\\nuser = null; // The object { name: 'John' } becomes unreachable and is garbage collected.",
    "Identify a memory leak caused by a forgotten setInterval or an unremoved event listener in a component.",
    "What makes an object eligible for garbage collection in JavaScript?",
    ["When it becomes unreachable from the root (e.g., window)", "When it is set to false", "When the function returns", "When the browser tab is minimized"], 0,
    "Unreachable objects cannot be accessed by the application and are safely deleted by the garbage collector."
  ],
  "auto-gen-8": ["exercise", "JavaScript", "ES Modules, Bundlers & Tree Shaking",
    "ES Modules (ESM) use import and export statements to share code. Bundlers like Webpack or Vite combine these modules into a single file. Tree shaking is the process of removing dead (unused) code from the final bundle.",
    "// math.js\\nexport const add = (a, b) => a + b;\\nexport const sub = (a, b) => a - b;\\n\\n// main.js\\nimport { add } from './math.js';\\n// 'sub' can be tree-shaken away",
    "Configure a basic Vite project, write modular functions, and observe how only imported functions end up in the build output.",
    "What is tree shaking?",
    ["Dead code elimination in module bundlers", "A method to parse JSON", "An animation library for React", "A way to compress image assets"], 0,
    "Tree shaking removes unused exports from the final JavaScript bundle, reducing file size."
  ],
  "auto-gen-9": ["project", "JavaScript", "Web Workers & Thread Offloading",
    "Web Workers allow you to run JavaScript in background threads, preventing CPU-intensive tasks from blocking the main UI thread. They communicate with the main thread via postMessage.",
    "// worker.js\\nonmessage = function(e) {\\n  let result = heavyComputation(e.data);\\n  postMessage(result);\\n}\\n// main.js\\nconst worker = new Worker('worker.js');\\nworker.postMessage(data);",
    "Build an application that calculates prime numbers. Offload the heavy loop to a Web Worker so the UI remains responsive.",
    "How do Web Workers communicate with the main thread?",
    ["Using the postMessage API", "By sharing memory directly", "Through localStorage", "Via HTTP requests"], 0,
    "Workers run in an isolated context and pass messages asynchronously using postMessage."
  ],
  "auto-gen-10": ["concept", "React", "React Server Components vs Client Components",
    "Server Components run exclusively on the server, reducing bundle size and allowing direct access to backend resources (like databases). Client Components run in the browser and support interactivity (useState, onClick).",
    "// Server Component\\nimport db from './db';\\nexport default async function Page() {\\n  const data = await db.query();\\n  return <div>{data}</div>;\\n}",
    "Refactor a Next.js page to extract interactive parts into a separate Client Component ('use client'), keeping the parent as a Server Component.",
    "Which feature is NOT available in a React Server Component?",
    ["useState and useEffect hooks", "Direct database access", "Async/await rendering", "Reading server files"], 0,
    "Server Components cannot use state, effects, or browser APIs because they never run in the browser."
  ],
  "auto-gen-11": ["exercise", "React", "Next.js App Router Layouts & Nested Routing",
    "Next.js App Router uses folders to define routes. layout.tsx wraps pages and preserves state across navigations. page.tsx is the UI unique to a route.",
    "// app/dashboard/layout.tsx\\nexport default function Layout({ children }) {\\n  return <><nav>Sidebar</nav><main>{children}</main></>;\\n}",
    "Create a nested routing structure with a shared dashboard layout and nested settings/profile pages.",
    "What is the purpose of layout.tsx in the Next.js App Router?",
    ["To share UI across multiple routes and preserve state during navigation", "To define API endpoints", "To handle 404 errors", "To configure Tailwind CSS"], 0,
    "Layouts wrap nested pages and do not re-render entirely on navigation, preserving their own state."
  ],
  "auto-gen-12": ["exercise", "React", "Server Actions Data Mutations & Form Validation",
    "Server Actions allow you to run asynchronous code directly on the server from client or server components, replacing traditional API routes for form submissions.",
    "export default function Form() {\\n  async function createPost(formData: FormData) {\\n    \\'use server\\'\\n    await db.post.insert({ title: formData.get('title') })\\n  }\\n  return <form action={createPost}><input name='title'/><button>Save</button></form>\\n}",
    "Implement a form with a Server Action that validates input using Zod, inserts data into a database, and calls revalidatePath.",
    "What directive is used to mark a function as a Server Action?",
    ["'use server'", "'use client'", "'server only'", "@server"], 0,
    "'use server' tells the bundler to create a secure endpoint for this function to be called from the client."
  ],
  "auto-gen-13": ["exercise", "React", "Custom React Hooks Abstraction & Context API",
    "Custom hooks allow you to extract and reuse stateful logic. The Context API provides a way to pass data through the component tree without prop drilling.",
    "function useWindowSize() {\\n  const [size, setSize] = useState([window.innerWidth, window.innerHeight]);\\n  useEffect(() => {\\n    const handleResize = () => setSize([window.innerWidth, window.innerHeight]);\\n    window.addEventListener('resize', handleResize);\\n    return () => window.removeEventListener('resize', handleResize);\\n  }, []);\\n  return size;\\n}",
    "Create a custom useAuth hook coupled with an AuthContext provider to manage user sessions application-wide.",
    "What must a custom hook's name start with?",
    ["use", "get", "hook", "It doesn't matter"], 0,
    "Custom hooks must start with 'use' so React can enforce the Rules of Hooks."
  ],
  "auto-gen-14": ["project", "React", "High-Performance Next.js Project",
    "Optimizing Next.js apps involves leveraging Server Components, implementing caching (fetch cache, memoization), streaming with Suspense, and optimizing images using next/image.",
    "import { Suspense } from 'react';\\nimport { Skeleton } from './Skeleton';\\nexport default function Page() {\\n  return (\\n    <Suspense fallback={<Skeleton />}>\\n      <SlowDataFetchingComponent />\\n    </Suspense>\\n  );\\n}",
    "Build a production-ready application that utilizes Suspense boundaries to stream UI chunks progressively to the client.",
    "How does React Suspense improve the user experience?",
    ["By showing a fallback UI while an asynchronous operation (like data fetching) completes", "By making API calls twice as fast", "By compressing images automatically", "By preventing CSS from blocking render"], 0,
    "Suspense lets you declaratively specify a loading state while a component waits for data or code to load."
  ],
  "auto-gen-15": ["concept", "Backend", "Node.js Runtime & HTTP Protocol Fundamentals",
    "Node.js is a runtime that executes JavaScript outside the browser using the V8 engine. It uses an event-driven, non-blocking I/O model. HTTP is the protocol used for transmitting hypermedia documents.",
    "const http = require('http');\\nconst server = http.createServer((req, res) => {\\n  res.writeHead(200, { 'Content-Type': 'text/plain' });\\n  res.end('Hello World');\\n});\\nserver.listen(3000);",
    "Create a raw Node.js HTTP server that parses the request URL and responds with different messages based on the route.",
    "What architectural pattern allows Node.js to handle thousands of concurrent connections efficiently?",
    ["Non-blocking, event-driven I/O", "Multi-threading with thread pools", "Synchronous blocking execution", "Object-Oriented Programming"], 0,
    "Node.js uses a single-threaded event loop to handle non-blocking I/O operations concurrently."
  ],
  "auto-gen-16": ["exercise", "Backend", "RESTful API Design Principles & Routing",
    "REST (Representational State Transfer) relies on stateless, client-server communication using standard HTTP methods (GET, POST, PUT, DELETE) and resource-based URLs (e.g., /users/123).",
    "app.get('/api/users/:id', async (req, res) => {\\n  const user = await db.getUser(req.params.id);\\n  res.json(user);\\n});",
    "Design a RESTful router using Express for a 'Books' resource supporting CRUD operations.",
    "Which HTTP method is idempotent and typically used to update an entire resource?",
    ["PUT", "POST", "PATCH", "OPTIONS"], 0,
    "PUT is idempotent (repeated requests have the same effect) and replaces the target resource entirely."
  ],
  "auto-gen-17": ["exercise", "Backend", "Request Validation & Error Handling Middleware",
    "Middleware are functions that execute during the request-response cycle. They can validate incoming payloads and catch errors to prevent server crashes and send standardized error responses.",
    "app.use((err, req, res, next) => {\\n  console.error(err.stack);\\n  res.status(500).json({ error: 'Internal Server Error' });\\n});",
    "Implement Zod validation middleware to verify POST bodies before they reach your controller logic.",
    "In Express, how does a middleware function pass control to the next function in the stack?",
    ["By calling the next() function", "By returning true", "By calling res.send()", "By throwing an exception"], 0,
    "Calling next() passes execution to the next middleware or route handler."
  ],
  "auto-gen-18": ["project", "Backend", "Build a Robust REST API Project",
    "A robust API features modular routing, environment variable configuration, secure headers, CORS support, validation, and a structured database abstraction layer.",
    "const express = require('express');\\nconst helmet = require('helmet');\\nconst app = express();\\napp.use(helmet());\\napp.use(express.json());\\n// ... route definitions",
    "Construct a full Express.js API serving a frontend application, complete with logging, error handling, and data persistence.",
    "What is the purpose of the CORS middleware?",
    ["To allow cross-origin HTTP requests from browsers", "To encrypt database passwords", "To compress HTTP responses", "To validate JSON schemas"], 0,
    "Cross-Origin Resource Sharing (CORS) is a security feature that controls how web pages request resources from a different domain."
  ],
  "auto-gen-19": ["concept", "Backend", "Relational Database Concepts & Normalization",
    "Relational databases organize data into tables with columns and rows. Normalization is the process of structuring a database to reduce redundancy and improve data integrity using primary and foreign keys.",
    "CREATE TABLE users (\\n  id SERIAL PRIMARY KEY,\\n  email VARCHAR(255) UNIQUE NOT NULL\\n);\\nCREATE TABLE posts (\\n  id SERIAL PRIMARY KEY,\\n  user_id INT REFERENCES users(id),\\n  title VARCHAR(255)\\n);",
    "Design a normalized schema for an e-commerce store with users, orders, and products.",
    "What is a Foreign Key?",
    ["A column that uniquely identifies a row in another table", "The main identifier for a table", "An encrypted password field", "A database index for fast searching"], 0,
    "A foreign key establishes a link between data in two tables."
  ],
  "auto-gen-20": ["exercise", "Backend", "SQL Queries: Joins, Grouping & Aggregation",
    "SQL allows complex data retrieval. JOINs combine rows from two or more tables based on a related column. GROUP BY groups rows that have the same values, used with aggregations like COUNT, SUM, or AVG.",
    "SELECT users.name, COUNT(posts.id) as post_count \\nFROM users \\nLEFT JOIN posts ON users.id = posts.user_id \\nGROUP BY users.id;",
    "Write a SQL query that retrieves the top 5 users with the highest number of completed courses.",
    "Which JOIN returns all records from the left table, and the matched records from the right table?",
    ["LEFT JOIN", "INNER JOIN", "RIGHT JOIN", "FULL OUTER JOIN"], 0,
    "LEFT JOIN returns all left table records, filling right table columns with NULL if no match exists."
  ],
  "auto-gen-21": ["exercise", "Backend", "PostgreSQL Client Integration & ORMs",
    "An ORM (Object-Relational Mapper) maps database tables to classes/objects in your code (e.g., Prisma, TypeORM), simplifying query writing and providing type safety.",
    "// Using Prisma ORM\\nconst newPost = await prisma.post.create({\\n  data: {\\n    title: 'Hello World',\\n    authorId: 1\\n  }\\n});",
    "Set up Prisma in a project, define a schema, run migrations, and write a script to query data.",
    "What is a major benefit of using an ORM like Prisma with TypeScript?",
    ["Auto-generated type definitions for database queries", "It makes the database run faster", "It eliminates the need for a database server", "It automatically writes CSS"], 0,
    "ORMs provide strong typing, ensuring your code expects the correct schema structures."
  ],
  "auto-gen-22": ["project", "Backend", "Database Integration Capstone Project",
    "Integrating a database into an application requires connection pooling, environment variable management (DATABASE_URL), and handling transaction failures gracefully.",
    "// Database connection pool setup\\nconst { Pool } = require('pg');\\nconst pool = new Pool({ connectionString: process.env.DATABASE_URL });\\nmodule.exports = pool;",
    "Build a backend API that executes complex transactions across multiple tables, ensuring rollback on failure.",
    "What is connection pooling?",
    ["Maintaining a cache of database connections to be reused for future requests", "Merging two databases together", "Using WebSockets for database queries", "Downloading the entire database to memory"], 0,
    "Connection pooling avoids the overhead of establishing a new database connection for every query."
  ],
  "auto-gen-23": ["exercise", "Backend", "GraphQL Schema Definition & Resolver Implementation",
    "GraphQL is a query language for APIs. Unlike REST, clients request exactly the data they need. It relies on a typed Schema and Resolvers that fetch the data for those fields.",
    "type Query {\\n  user(id: ID!): User\\n}\\ntype User {\\n  id: ID!\\n  name: String!\\n  posts: [Post]\\n}",
    "Define a GraphQL schema for a blog and implement resolvers that fetch data from a mock database.",
    "In GraphQL, what determines the structure of the response?",
    ["The client's query", "The server's routing setup", "The database schema", "The HTTP method used"], 0,
    "The client explicitly specifies the fields it wants in the query, and the response matches that shape exactly."
  ],
  "auto-gen-24": ["concept", "Backend", "PostgreSQL Indexing & Query Optimization",
    "Indexes improve data retrieval speed by creating a structured lookup table (like a book index). However, they slow down write operations (INSERT, UPDATE) because the index must also be updated.",
    "CREATE INDEX idx_users_email ON users(email);\\nEXPLAIN ANALYZE SELECT * FROM users WHERE email = 'test@example.com';",
    "Use EXPLAIN ANALYZE on a large table to observe the performance difference before and after adding an index.",
    "When should you typically add an index to a database column?",
    ["When the column is frequently used in WHERE clauses or JOIN conditions", "On every single column in the table", "Only on columns containing boolean values", "When the table has less than 100 rows"], 0,
    "Indexes dramatically speed up lookups for frequently queried columns."
  ],
  "auto-gen-25": ["exercise", "Backend", "Authentication, JWT & Granular Row Level Security (RLS)",
    "JSON Web Tokens (JWT) are securely signed tokens used for stateless authentication. Row Level Security (RLS) in databases like PostgreSQL restricts which rows a user can read or modify based on their identity.",
    "ALTER TABLE user_data ENABLE ROW LEVEL SECURITY;\\nCREATE POLICY 'Users can only view their own data'\\nON user_data FOR SELECT\\nUSING (auth.uid() = user_id);",
    "Implement JWT verification middleware and configure PostgreSQL RLS policies in a Supabase project.",
    "What prevents a JWT from being forged or tampered with by the client?",
    ["The cryptographic signature verified by the server's secret key", "It is encrypted using AES-256", "It is stored in an HttpOnly cookie", "It automatically expires"], 0,
    "The signature guarantees that the token payload has not been modified since the server issued it."
  ],
  "auto-gen-26": ["project", "Backend", "Secure Multi-Tenant Enterprise Backend Project",
    "Multi-tenant architectures serve multiple organizations (tenants) from a single database. Tenant isolation must be strictly enforced using RLS or tenant_id checks on every query.",
    "SELECT * FROM invoices WHERE tenant_id = $1 AND invoice_id = $2;",
    "Build a multi-tenant API where users belong to organizations, and ensure users cannot access data outside their organization.",
    "What is the primary security risk in a multi-tenant application?",
    ["Cross-tenant data leakage", "SQL Injection", "Cross-Site Scripting (XSS)", "Denial of Service (DoS)"], 0,
    "Failing to enforce tenant isolation properly allows one customer to view or modify another customer's data."
  ],
  "auto-gen-27": ["concept", "Fullstack", "Serverless Deployments & Edge Infrastructure",
    "Serverless functions (like AWS Lambda, Vercel) scale to zero and bill per execution. Edge computing runs logic geographically close to the user via CDN nodes, reducing latency.",
    "export const config = { runtime: 'edge' };\\nexport default function handler(req) {\\n  return new Response('Hello from the Edge!');\\n}",
    "Deploy a Next.js application to Vercel and write an Edge Middleware function to rewrite paths based on geolocation.",
    "What is a primary characteristic of serverless computing?",
    ["Automatic scaling and pay-per-execution billing", "You manage the physical hardware", "Server instances run 24/7 constantly", "It only supports JavaScript"], 0,
    "Serverless platforms automatically handle scaling up and scaling down to zero."
  ],
  "auto-gen-28": ["exercise", "Fullstack", "Automated CI/CD Pipeline Configuration",
    "CI/CD (Continuous Integration/Continuous Deployment) automates testing and deployment. GitHub Actions allows you to define workflows in YAML that run on push or PR.",
    "name: CI\\non: [push]\\njobs:\\n  test:\\n    runs-on: ubuntu-latest\\n    steps:\\n      - uses: actions/checkout@v3\\n      - run: npm ci\\n      - run: npm test",
    "Create a GitHub Actions workflow that runs ESLint and Jest tests automatically on every pull request.",
    "What is the purpose of Continuous Integration (CI)?",
    ["To automatically build and test code changes frequently", "To deploy code to production immediately", "To write code automatically using AI", "To manage database migrations"], 0,
    "CI ensures that new code changes integrate smoothly and pass automated quality checks."
  ],
  "auto-gen-29": ["project", "Fullstack", "Real User Monitoring & Core Web Vitals Optimization",
    "Core Web Vitals are Google's metrics for UX: LCP (Largest Contentful Paint), FID (First Input Delay), and CLS (Cumulative Layout Shift). Optimizing them involves lazy loading, optimizing fonts/images, and reducing JS execution.",
    "import Image from 'next/image';\\n// Automatically optimizes webp, handles lazy loading and prevents CLS\\n<Image src='/hero.jpg' width={800} height={400} alt='Hero' />",
    "Audit a web application using Lighthouse, identify a CLS issue caused by unoptimized images, and fix it.",
    "Which Core Web Vital metric measures visual stability (elements moving unexpectedly)?",
    ["Cumulative Layout Shift (CLS)", "Largest Contentful Paint (LCP)", "First Input Delay (FID)", "Time to First Byte (TTFB)"], 0,
    "CLS measures how much the page layout shifts unexpectedly during loading."
  ],
  "auto-gen-30": ["concept", "AI", "Large Language Model Architecture Overview",
    "LLMs like GPT-4 are based on the Transformer architecture. They process text using self-attention mechanisms, predicting the most probable next token based on the provided context window.",
    "// Example representation of token generation\\nlet context = 'The sky is';\\nlet nextToken = model.predict(context); // ' blue'",
    "Explore a token counting tool to see how sentences are broken down into sub-word tokens by byte-pair encoding (BPE).",
    "What is the primary underlying architecture of modern LLMs?",
    ["The Transformer", "Recurrent Neural Networks (RNN)", "Convolutional Neural Networks (CNN)", "Decision Trees"], 0,
    "The Transformer architecture, introduced in 2017, relies on self-attention and enables massive parallelization."
  ],
  "auto-gen-31": ["exercise", "AI", "API Integration, Authentication & Streaming Responses",
    "Integrating AI involves calling APIs (e.g., OpenAI). For responsive UX, responses are often streamed back chunk-by-chunk using Server-Sent Events (SSE) instead of waiting for the full generation.",
    "const completion = await openai.chat.completions.create({\\n  model: 'gpt-4',\\n  messages: [{ role: 'user', content: 'Hello!' }],\\n  stream: true,\\n});\\nfor await (const chunk of completion) {\\n  process.stdout.write(chunk.choices[0]?.delta?.content || '');\\n}",
    "Build a Node.js endpoint that streams an AI response back to a client application in real-time.",
    "Why is streaming important in LLM chat applications?",
    ["It reduces perceived latency by displaying text as it is generated", "It reduces API costs", "It makes the AI smarter", "It prevents the AI from hallucinating"], 0,
    "Streaming improves UX significantly by showing output immediately, rather than waiting seconds for the whole response."
  ],
  "auto-gen-32": ["exercise", "AI", "Advanced Prompt Engineering & System Directives",
    "Prompt engineering involves crafting inputs to guide the model. System prompts define the model's persona and rules. Few-shot prompting provides examples to guide the output format.",
    "const messages = [\\n  { role: 'system', content: 'You are an API that only responds with valid JSON.' },\\n  { role: 'user', content: 'Extract names from: Alice and Bob' }\\n];",
    "Write a system prompt that forces the AI to evaluate a coding assignment and output a strict JSON grading rubric.",
    "What is 'few-shot' prompting?",
    ["Providing the model with a few examples of desired input-output pairs", "Giving the model limited time to respond", "Using a very short prompt", "Prompting the model multiple times in parallel"], 0,
    "Few-shot prompting shows the model exactly how you want it to behave using examples."
  ],
  "auto-gen-33": ["project", "AI", "AI Assistant Capstone Project",
    "An AI assistant needs conversation history management, context truncation, and robust error handling to maintain a coherent multi-turn dialogue.",
    "// Maintaining context window\\nlet conversationHistory = [];\\nfunction chat(userInput) {\\n  conversationHistory.push({ role: 'user', content: userInput });\\n  // truncate history if it exceeds token limits...\\n}",
    "Build a full-stack AI chat interface that remembers past messages and uses a custom system prompt.",
    "Why must conversation history be managed carefully in an AI app?",
    ["Because LLMs have a maximum context window (token limit)", "Because it slows down the database", "Because the AI forgets things automatically", "To save on local storage space"], 0,
    "If the conversation exceeds the model's token limit, the API request will fail, necessitating truncation."
  ],
  "auto-gen-34": ["concept", "AI", "Text Embeddings & Semantic Vector Space",
    "Embeddings convert text into high-dimensional numerical vectors. Texts with similar semantic meanings will have vectors that are closer together in this mathematical space, enabling semantic search.",
    "const vector1 = [0.1, 0.5, -0.2]; // 'Dog'\\nconst vector2 = [0.12, 0.48, -0.19]; // 'Puppy'\\n// Cosine similarity between these vectors will be high.",
    "Generate embeddings for several sentences and calculate the cosine similarity between them using a script.",
    "What do text embeddings capture that keyword search does not?",
    ["Semantic meaning and context", "Exact spelling matches", "Punctuation errors", "Word counts"], 0,
    "Embeddings capture the underlying meaning, so 'car' and 'automobile' are recognized as similar."
  ],
  "auto-gen-35": ["exercise", "AI", "Vector Database Setup & Similarity Search",
    "Vector databases (like Pinecone, Qdrant, or pgvector) are designed to store embeddings and perform rapid similarity searches (k-nearest neighbors) at scale.",
    "// PostgreSQL pgvector extension\\nSELECT text_chunk FROM document_embeddings \\nORDER BY embedding <=> '[0.1, 0.2, 0.3]' LIMIT 5;",
    "Set up a local instance of pgvector, insert text embeddings, and query for the 3 most similar documents to a search query.",
    "What is the primary operation performed by a Vector Database?",
    ["Similarity Search (finding vectors closest to a query vector)", "Relational table joins", "Key-value caching", "Full-text indexing"], 0,
    "Vector databases specialize in calculating mathematical distances between high-dimensional vectors to find similarities."
  ],
  "auto-gen-36": ["project", "AI", "RAG Pipeline Orchestration",
    "Retrieval-Augmented Generation (RAG) combines semantic search with LLMs. Step 1: Embed user query. Step 2: Search vector DB for relevant context. Step 3: Pass context + query to the LLM to generate an informed answer.",
    "const context = await vectorDb.search(userQuery);\\nconst prompt = \`Answer the query using ONLY this context: \${context}\\nQuery: \${userQuery}\`;\\nconst answer = await llm.generate(prompt);",
    "Build a script that ingests a PDF, chunks the text, creates embeddings, and allows a user to ask questions about the document.",
    "What problem does RAG primarily solve in Large Language Models?",
    ["Hallucinations and lack of access to private/recent data", "Slow response times", "High API costs", "Context window limitations"], 0,
    "RAG grounds the LLM by providing factual, retrieved context in the prompt, reducing hallucinations."
  ],
  "auto-gen-37": ["concept", "Generic", "Domain Conceptual Architecture",
    "Understanding the conceptual architecture of a new domain involves mapping its core paradigms, data flow, and separation of concerns before writing code.",
    "// Architecture mapping\\n// UI Layer <-> Business Logic <-> Data Access Layer",
    "Draw a block diagram of the domain architecture identifying the key components and their interactions.",
    "Why is conceptual architecture important?",
    ["It provides a high-level roadmap and structural understanding before implementation", "It writes the code for you", "It makes the app run faster", "It bypasses security checks"], 0,
    "A strong conceptual understanding prevents fundamental structural mistakes during implementation."
  ],
  "auto-gen-38": ["exercise", "Generic", "Environment Setup & Tooling Configuration",
    "Setting up the development environment correctly (compilers, linters, SDKs, environment variables) is a critical prerequisite for any project.",
    "# Example setup commands\\nnpm install\\ncp .env.example .env\\nnpm run dev",
    "Follow the setup documentation to initialize the project, install dependencies, and successfully run the local development server.",
    "What is the purpose of an .env file?",
    ["To store configuration and secrets securely outside of version control", "To style the application", "To define database schemas", "To list project dependencies"], 0,
    "Environment variables keep secrets like API keys out of source code repositories."
  ],
  "auto-gen-39": ["project", "Generic", "First Practical Implementation Project",
    "The first practical implementation (a 'Hello World' or 'Todo App') validates that the environment is working and the developer understands the basic syntax and flow.",
    "function bootstrap() {\\n  console.log('System initialized and ready.');\\n}\\nbootstrap();",
    "Build the minimal viable implementation of the domain's core concept from scratch.",
    "What is the goal of a minimal viable implementation?",
    ["To prove the end-to-end setup works and grasp the core mechanics", "To build a production-ready enterprise app", "To pass a coding interview", "To optimize server performance"], 0,
    "Building a minimal version proves understanding of the fundamentals and verifies the environment."
  ],
  "auto-gen-40": ["concept", "Generic", "Standard Architecture Patterns",
    "Design patterns (like MVC, Singleton, Factory, Repository) provide proven solutions to common architectural problems, making code more maintainable and readable to other developers.",
    "class Singleton {\\n  static instance;\\n  constructor() {\\n    if (Singleton.instance) return Singleton.instance;\\n    Singleton.instance = this;\\n  }\\n}",
    "Identify where the Model-View-Controller (MVC) pattern is used within your current framework.",
    "What is a software design pattern?",
    ["A reusable solution to a commonly occurring problem in software design", "A specific programming language", "A UI component library", "A database query technique"], 0,
    "Patterns are proven templates for solving recurring architectural challenges."
  ],
  "auto-gen-41": ["exercise", "Generic", "Implementation & Debugging Workflow",
    "Effective debugging involves isolating variables, reading stack traces, using breakpoints (or console logs), and searching for root causes systematically rather than guessing.",
    "try {\\n  riskyOperation();\\n} catch (error) {\\n  console.error('Operation failed at step 2:', error.stack);\\n}",
    "Introduce a bug into your application and use the debugger tool in your IDE to step through the code and inspect variable states.",
    "What is a stack trace?",
    ["A report of the active stack frames showing the function calls that led to an error", "A list of all variables in the application", "A network activity log", "A database backup file"], 0,
    "The stack trace shows exactly which function called which function, leading up to the crash."
  ],
  "auto-gen-42": ["project", "Generic", "Comprehensive Feature Integration Project",
    "Feature integration requires combining multiple sub-systems (UI, API, database) into a cohesive workflow, handling edge cases and loading states.",
    "// End-to-end feature flow\\nUI.onSubmit(async (data) => {\\n  UI.setLoading(true);\\n  await API.saveData(data);\\n  UI.setLoading(false);\\n});",
    "Implement a complete user flow from frontend click to database persistence and back to UI update.",
    "Why are loading states important in feature integration?",
    ["They provide visual feedback to the user during asynchronous operations", "They make the code run faster", "They prevent hackers from attacking", "They compile the CSS"], 0,
    "Loading states prevent user frustration and duplicate actions while waiting for the backend."
  ],
  "auto-gen-43": ["concept", "Generic", "Advanced System Design & Scalability",
    "System design at scale involves load balancing, caching (Redis), asynchronous message queues (RabbitMQ/Kafka), and horizontal vs vertical scaling.",
    "// Caching strategy example\\nlet data = cache.get(key);\\nif (!data) {\\n  data = await db.query(key);\\n  cache.set(key, data, { ttl: 3600 });\\n}",
    "Design a system architecture diagram for an application expecting 1 million daily active users.",
    "What is horizontal scaling?",
    ["Adding more server instances to distribute the load", "Upgrading a single server with more RAM and CPU", "Using a faster database", "Minifying JavaScript code"], 0,
    "Horizontal scaling involves provisioning additional servers behind a load balancer."
  ],
  "auto-gen-44": ["exercise", "Generic", "Performance Profiling & Optimization",
    "Profiling involves measuring memory usage, CPU time, and network latency to identify bottlenecks. Optimization might involve memoization, indexing, or bundle splitting.",
    "console.time('heavyTask');\\nperformHeavyTask();\\nconsole.timeEnd('heavyTask');",
    "Use Chrome DevTools Performance tab to record a profile of your app, identify a slow function, and optimize it.",
    "What is memoization?",
    ["Caching the result of an expensive function call based on its inputs", "Writing memos in the code comments", "A type of database index", "A memory leak"], 0,
    "Memoization stores function results so that repeated calls with the same inputs return instantly."
  ],
  "auto-gen-45": ["project", "Generic", "Production Readiness Capstone Deployment",
    "Production readiness requires configuring environment variables securely, setting up CI/CD, enabling HTTPS, configuring domain names, and establishing logging/monitoring.",
    "// Production logging\\nconst logger = require('winston');\\nlogger.info('Server started in production mode on port 443');",
    "Deploy your application to a production environment, configure a custom domain, and secure it with an SSL certificate.",
    "Which is a critical checklist item before going to production?",
    ["Ensuring all secret keys are managed securely via environment variables", "Leaving debug mode enabled", "Committing the .env file to GitHub", "Using console.log for all monitoring"], 0,
    "Secret management is critical to prevent API keys and database credentials from being compromised."
  ]
};

const filePath = 'lib/generator/content-registry.ts';
let content = fs.readFileSync(filePath, 'utf8');

for (const [id, values] of Object.entries(data)) {
  const [type, topic, title, concept, code, practical, q, options, correct, expl] = values;
  
  const blockObj = {
      id: id,
      title: title,
      type: type,
      objective: concept.split('.')[0] + '.',
      concept_guide: concept,
      code_example: code,
      practical_exercise: practical,
      checkpoint_question: q,
      checkpoint_options: options,
      checkpoint_correct_index: correct,
      checkpoint_explanation: expl,
      topic: topic,
      difficulty: "Intermediate"
  };
  
  const block = "\\n" + JSON.stringify(blockObj, null, 6).slice(1, -1) + "  }";

  // Replace existing block inside the JSON structure
  const regex = new RegExp(`"\\s*${id}\\s*"\\s*:\\s*\\{[\\s\\S]*?"difficulty"\\s*:\\s*"Adaptive"\\s*\\}`, 'g');
  if (content.match(regex)) {
      content = content.replace(regex, `"${id}": {` + block);
  }
}

fs.writeFileSync(filePath, content);
console.log('Successfully updated content-registry.ts');
